[workspace]
name = "isce2grimp"
platforms = ["linux-64", "osx-64"]
channels = ["conda-forge"]

[dependencies]
python = "==3.11.6"
geopandas = "==0.14.4"
isce2 = "==2.6.3"
numpy = "==1.26.4"
pyproj = "==3.5.0"
pyyaml = "==6.0.1"
rasterio = "==1.3.6"
scipy = "==1.13.0"
setuptools = "==69.5.1"

[pypi-dependencies]
isce2grimp = {path = ".", editable = true}

[environments]
dev = {features = ["dev"], solve-group = "default"}

[feature.dev.dependencies]
pytest = "*"
ipython = ">=9.10.0,<10"

[tasks]
update_inventory = "update_inventory"

[feature.dev.tasks]
test = "pytest"
